$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline

display_name: training-pipeline
experiment_name: training-pipeline
description: Pipeline to build an MLFlow model to determine the likelihood of IRIS.

inputs:
  blob_account_name: 'irisblobs'
  blob_container_name: 'models'
  datasets_container_name: 'datasets'

settings:
  default_compute: azureml:cpu-cluster-4core
  continue_on_step_failure: false

jobs:
  train_model:
    type: command
    component: azureml:component_pipeline_cli_train@latest
    inputs:
      blob_account_name: ${{parent.inputs.blob_account_name}}
      blob_container_name: ${{parent.inputs.blob_container_name}}
      training_datasets:
        type: uri_folder
        path: azureml:IrisTrainFileData@latest
      test_datasets:
        type: uri_folder
        path: azureml:IrisTestFileData@latest
    outputs:
      output_folder:
        mode: rw_mount
  evaluate_model:
    type: command
    component: azureml:component_pipeline_cli_evaluate@latest
    inputs:
      blob_account_name: ${{parent.inputs.blob_account_name}}
      blob_container_name: ${{parent.inputs.blob_container_name}}
      test_datasets:
        type: uri_folder
        path: azureml:IrisTestFileData@latest
      train_input: ${{parent.jobs.train_model.outputs.output_folder}}
    outputs:
      evaluate_output_folder:
        mode: rw_mount
  deploy_model:
    type: command
    component: azureml:component_pipeline_cli_deploy@latest
    inputs:
      evaluate_input: ${{parent.jobs.evaluate_model.outputs.evaluate_output_folder}}