name: iris_pipeline
dependencies:
- python=3.8.13
- pip:
  # - azureml-sdk[automl]
  # - opencv-python-headless
  # - tensorflow
  - azureml-sdk[automl]
  - tensorflow-gpu==2.11.0
  - opencv-python-headless
  - keras==2.11.0
  - Keras-Preprocessing
channels:
  - anaconda
  - conda-forge